<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Formulir Klaim</name>
   <tag></tag>
   <elementGuidId>03ef8a79-32d9-436f-a5dd-7a664fdb17b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;ShowFormClaimData_pyDisplayHarness_126&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='ShowFormClaimData_pyDisplayHarness_126']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9d814bc-bff6-46ec-af60-9c4ce2724999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20201222143831032389821</value>
      <webElementGuid>277097e1-da17-4c14-9a67-b7ca165ddc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;pyDisplayHarness&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9YjFkMTFkNzdhNDg0NDY4YTdiMTJiMTQxMzM3YTZkNGY0YTUyM2VkODU4NDA4ZjA0MTMzODllMGI5ZmE0NmQyNGY5NGIwNzBiOWU1ZmVhODQyOGMxMjgzODczODY5NjRmNGVjNTNlODhmN2YzYjIwYTBmYjk2NDZjMzFmMmQwOTFmMTk2YjI1MmQzYmFjOTU3Y2Y1M2JiZGFhOGZmZDhiM2Q5YjkzMTIxZjE5YTBiMjNkMDZhYWE0NWZiODUzNjVmODQxYmI3YTJjZTFhM2MzYjk0OTIzYWQwNWVkZWEzMTUyN2M3YjZjZmQxMDA3Y2Y3NjAzMWZjYzEyNThlNjBiNQ%3D%3D*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ZThkZDhjYmE2YjBlMGUxODE1NDg3ZGZhYmRiNDIzMWQ1ZDE1YWZhYjc0NjVhMDU5NjBjNDQwNGQ4ZDNlMmFkY2VjNmM3NTQwNWM4OWYxYmQ3MzJiNGQ0NTY0MjE2MWVkMDJhMWNlZGEzMDQ0ZmY3ZWM1ZTlkNWJkZDA5OGY1ODFiNjFiZjI1MmU3MWYwYTI3ZTM2ZTg0YzczYjkyMjA0MjE1M2Y5NTQ4MTU4NTM1MzY0ZTI3YTRiMTMxNDBkZTA2*&quot;,{},{}],&quot;pyDisplayHarness&quot;]],[&quot;setMobileTransition&quot;,[&quot;pega.mobile.transitions.NONE&quot;]],[&quot;openAssignment&quot;,[&quot;#~pyDisplayHarness.IDPEGA~#&quot;,&quot;f902556a-7bb3-4699-82dd-46f26a07daf0&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;#~pyDisplayHarness.pyIsOfflineEnabled~#&quot;,{&quot;target&quot;:&quot;primary&quot;,&quot;pyReloadAlways&quot;:&quot;false&quot;}]]]</value>
      <webElementGuid>02ced270-e8cb-4bfe-b48a-d153f836d6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShowFormClaimData_pyDisplayHarness_126</value>
      <webElementGuid>9280c034-9f80-4ac7-97ce-6d20e7ecf3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>6b739f46-10f8-41fe-a5f7-88e6ebc31414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9234420c-a6f6-4504-91c1-de732eae7812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Formulir Klaim</value>
      <webElementGuid>1f6d1fab-1d85-46dd-8a6b-eef9a0f3ae16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l2&quot;)/div[@class=&quot;screen-layout-region-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default margin-b-1x&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[1]/div[@class=&quot;flex content layout-content-stacked  content-stacked  content-items-maxwidth&quot;]/div[@class=&quot;content-item content-layout item-2 remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-top-spacing remove-left-spacing remove-bottom-spacing remove-right-spacing flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[1]/div[@class=&quot;flex content layout-content-stacked  content-stacked  content-items-maxwidth&quot;]/div[@class=&quot;content-item content-layout item-1 remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>0e0580fa-b27b-42d7-9880-a3e9430a8391</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='ShowFormClaimData_pyDisplayHarness_126']</value>
      <webElementGuid>c6ae8901-1da8-418f-81e2-85418fc3117b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='RULE_KEY']/div/div/div/div/div/span/button)[2]</value>
      <webElementGuid>642807f3-1959-4f9c-a55c-cccf93d8a2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah'])[2]/following::button[1]</value>
      <webElementGuid>abb430b1-fd0a-431c-8c7b-e17f467cf7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[2]/following::button[1]</value>
      <webElementGuid>a9afea4e-c5de-4a47-9939-0f9851ee4059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Data'])[4]/preceding::button[1]</value>
      <webElementGuid>c262c33f-9a9e-42e9-82ea-83df15010c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[3]/preceding::button[2]</value>
      <webElementGuid>3e043af9-11ff-4546-8d78-0f9aed3ea457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ Formulir Klaim']/parent::*</value>
      <webElementGuid>09dbf086-f67a-4fe8-8f8d-1b3e36c325aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span/div/div/div/div/div/div/span/button</value>
      <webElementGuid>a1f1e646-acd3-4090-8d76-f757b7375bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'ShowFormClaimData_pyDisplayHarness_126' and @type = 'button' and (text() = '+ Formulir Klaim' or . = '+ Formulir Klaim')]</value>
      <webElementGuid>ba47bb33-3243-485d-88e7-b6d288d47941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
