<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah</name>
   <tag></tag>
   <elementGuidId>23f4c78c-54b2-4600-95d8-a56dbaf29a3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;UploadFotoPanel_pyWorkPage_61&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='UploadFotoPanel_pyWorkPage_61']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b4e5660-f605-4838-b626-5fb7167021c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2021010413281907583223</value>
      <webElementGuid>27b67746-a3ed-435d-8c96-c3c3c220834c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;processAction&quot;, [&quot;UploadFotoKerusakan&quot;,&quot;true&quot;,&quot;:event&quot;,&quot;&quot;,&quot;Rule-HTML-Section&quot;,&quot;&quot;,&quot;pzModalTemplate&quot;,&quot;%7B%22mobile%22%3A%7B%22reveal%22%3A%7B%22effect%22%3A%22anim-null%22%7D%2C%22isCustomDismiss%22%3A%22true%22%2C%22dismiss%22%3A%7B%22effect%22%3A%22anim-null%22%7D%7D%7D&quot;,&quot;true&quot;,&quot;ASM-FW-ICMS-Work-FormulirClaim&quot;,&quot;ASM-FW-ICMS-Work-FormulirClaim&quot;,&quot;true&quot;,&quot;true&quot;,&quot;&quot;,&quot;&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ODdmOTI4ZjI5YzgwZTQ3MjZlMjYwNGYxY2ZlYWVlNzc5N2Q0YjZkY2NjNDA3ZTQxYzVkN2VhYTI2OGMwNDBmOGJkNTZlOTQwYmQ0OTk1NGZmMjRhMTFhNmZlNGVmYzdkYzI0YmM0ODg5MWY4N2RhZTMxZGE1OTZhMjE0YTFjZGM0NDBlY2M1NDdkMmE1NjU4M2I1N2MxYjNiZWQ5MTNhOTJlYTg0YTI4OTU1NmIzMGMxZWNjOTQyN2NmMjJiNDRj*&quot;,{},{}],&quot;pyWorkPage&quot;]]]</value>
      <webElementGuid>71a6ab83-08b0-4a56-9945-985bcb4d7cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadFotoPanel_pyWorkPage_61</value>
      <webElementGuid>42aaced9-b144-47b4-b34e-6177317ca643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>820fdc97-c0cf-466e-bfe8-1e56e93959a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ab24fd5-1c18-45df-bb9d-091572a9f30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Unggah</value>
      <webElementGuid>f5d2a937-d83f-43ca-a0d7-fb90a3dfe8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HARNESS_CONTENT&quot;)/div[@class=&quot;workarea-view-scroll-wrapper&quot;]/section[@class=&quot;workarea-view-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked  content-items-maxwidth&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-left-spacing remove-right-spacing flex flex-row no-margin-bottom&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-action_area  clear-floated-layouts&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-top-spacing remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@id=&quot;pyFlowActionHTML&quot;]/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@id=&quot;EXPAND-OUTERFRAME&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[1]/div[@class=&quot;flex content layout-content-default  content-default  content-items-maxwidth&quot;]/div[@class=&quot;content-item content-layout item-1 remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked  content-items-maxwidth&quot;]/div[@class=&quot;content-item content-field item-1 remove-left-spacing remove-right-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>8f101f5d-d032-474c-ba0e-560f127c5479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='UploadFotoPanel_pyWorkPage_61']</value>
      <webElementGuid>68b5d66b-60ce-4668-b6b1-110c14f08107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/div/div/div/span/button</value>
      <webElementGuid>fe13d45d-396d-489f-a23e-706e2df88701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto Kerusakan Panel'])[1]/following::button[1]</value>
      <webElementGuid>e71b80b7-5f18-4496-8e7e-576b2208eeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[2]/following::button[4]</value>
      <webElementGuid>c470b20b-4217-4a37-b032-eea3e5c60c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambar'])[1]/preceding::button[1]</value>
      <webElementGuid>29a434f1-bb37-408a-8a7d-e9ea50af7fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[3]/preceding::button[1]</value>
      <webElementGuid>2ede4bf1-d31d-4465-828f-6c0c0e787874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+Unggah']/parent::*</value>
      <webElementGuid>a6767bd1-5489-4f1f-896b-a91610a4fc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/div/span/button</value>
      <webElementGuid>d55b8874-81a0-45f1-b694-e55286cb653a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'UploadFotoPanel_pyWorkPage_61' and @type = 'button' and (text() = '+Unggah' or . = '+Unggah')]</value>
      <webElementGuid>db3f1183-eed9-4712-96f8-d48e0ed30035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
