<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>4fa349b2-4f3d-4ff4-ad5b-f23838732ce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;UploadFotoPanel_pyWorkPage_98&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='UploadFotoPanel_pyWorkPage_98']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd3c1578-269b-427e-9832-79ed00e579db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202101061013140464130577</value>
      <webElementGuid>525de9b4-4874-43eb-a2d2-124b342b0c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;pyWorkPage&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ZmZiNWYzN2RmYzQwNTVhNjhjN2VmNGQ3OGI1OWVjZTRhZGFiN2Y3MmQ4MTkzMWI0Mzk5MGYzZmZjMWEyOTRlNmRmMzRjMjhjYTA0ZjVhMmUzOTNjODc3MmUyNGE2OTdmYTVkNDMxNDE0NTI1MWFkMDlkMmIxNGY4OTFhYWQ1NzU%3D*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;ViewUploadFileForm&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ODdmOTI4ZjI5YzgwZTQ3MjZlMjYwNGYxY2ZlYWVlNzc5N2Q0YjZkY2NjNDA3ZTQxYzVkN2VhYTI2OGMwNDBmOGJkNTZlOTQwYmQ0OTk1NGZmMjRhMTFhNmZlNGVmYzdkYzI0YmM0ODg5MWY4N2RhZTMxZGE1OTZhMjE0YTFjZGM0NDBlY2M1NDdkMmE1NjU4M2I1N2MxYjNiZWQ5MTNhOTEwMjA3NmM5OTUxYzE0MzBjYWUxNTFlYzZmMGFiYTI2YTExZTEzOWI2ODRlMWI1MjZjNjFiZjJlY2QxMDEwNGJiYWI5ODA2MjdlZjlhOGQ5ODA0NGE1ODUxNmQ2MTcyNzM2Y2VmNWNhMjZkZGVhYTY5NGJlMWE0NmI2NzUzYjM1MmEyNzQ3MWQ0NmE4MDA3ZDBiYzE3ZTg1MmI3NjE1YTNjNWQ5YTY1MjExYWNiMTc3MDNiNjM3NjkyZmE3YjE1MjZlZDVjNzI5ZDM4MGNjYjc3OTUyNWNlMzhjMTVmZThjNmU0YzczY2RlNzIzNTIxZWE2Y2JkNTQ1YWIxZTA3NjY%3D*&quot;,{&quot;idForm&quot;:&quot;&quot;,&quot;Jenisform&quot;:&quot;&quot;},{}],&quot;pyWorkPage&quot;]]]</value>
      <webElementGuid>d4cccf95-058a-48fb-8a88-481e865ec179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadFotoPanel_pyWorkPage_98</value>
      <webElementGuid>6ef22477-dcdd-4c46-a5c8-e57f72efbd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pzhc pzbutton</value>
      <webElementGuid>bf32c800-4b14-4e5d-9752-fc1ec7a23d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95086b6c-1fac-4cb7-b4ca-1f20ebe2d98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>c5505347-11b0-4d26-9c7f-25860ee340ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HARNESS_CONTENT&quot;)/div[@class=&quot;workarea-view-scroll-wrapper&quot;]/section[@class=&quot;workarea-view-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked  content-items-maxwidth&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-left-spacing remove-right-spacing flex flex-row no-margin-bottom&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-action_area  clear-floated-layouts&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-top-spacing remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@id=&quot;pyFlowActionHTML&quot;]/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default  float-right set-width-auto&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-default  content-default set-width-auto&quot;]/div[@class=&quot;content-item content-layout item-1 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;pzhc pzbutton&quot;]</value>
      <webElementGuid>8c3cbed9-5f19-4c1b-b5d5-3f1c22592564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='UploadFotoPanel_pyWorkPage_98']</value>
      <webElementGuid>21df468c-97ae-43a8-bf90-8787f2d9332d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[6]/div/div/div/div/div/span/button</value>
      <webElementGuid>389cb799-7b5d-4d05-9d94-bd4fa5dcf450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[2]/following::button[1]</value>
      <webElementGuid>6f9afcbb-b701-4d34-be4a-c6e0b4602b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Gambar'])[2]/following::button[2]</value>
      <webElementGuid>6f0b0c5a-a479-4462-b785-829bfa61ddaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::button[1]</value>
      <webElementGuid>6c00efb3-8980-480a-8bc9-86cb71ca32c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UploadDokumenFormClaimAllDocument_FA'])[1]/preceding::button[2]</value>
      <webElementGuid>a4466f26-6e3b-4393-b471-5bccf3cc6b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>7c3a6598-36b8-4e61-b16d-1e1bba015706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/span/button</value>
      <webElementGuid>d1f02797-c90c-4319-ba23-fd3ac849073b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'UploadFotoPanel_pyWorkPage_98' and @type = 'button' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>81dc10d5-be66-4704-936d-db9fd38e0801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
