<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>a83a1d54-9997-4fc2-9dfb-0e2dc0e62d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ModalButtonSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ModalButtonSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b994614a-b015-4d42-a800-66d67443f397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonTdButton</value>
      <webElementGuid>0d19fb6d-f430-44cb-a2b1-96d3263cad09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pega_version</name>
      <type>Main</type>
      <value>HTMLPROPERTY</value>
      <webElementGuid>44d7adcf-05df-4d7b-b558-0a8f16681606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ModalButtonSubmit</value>
      <webElementGuid>0e065b03-7f0d-4388-a22f-21092d16829b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(typeof(pega) !='undefined' &amp;&amp; pega.u.d) setUserStart(); doModalAction(pega.u.d.submitModalDlgParam,event); </value>
      <webElementGuid>73e1bf18-4692-49e5-9fcc-3637aeb4e856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89236b45-84a9-4be9-8310-a56f42cc7c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click here to submit work</value>
      <webElementGuid>b8ebb62e-8776-4ec6-acdd-8a989a857eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Click here to submit work</value>
      <webElementGuid>525b8eb6-8e20-4b7a-83b3-b03201a1a10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>non-auto</value>
      <webElementGuid>e62ebdf7-566a-4463-ae00-12422bd36f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Submit </value>
      <webElementGuid>377e163b-1a07-4a5b-8654-74772f9eb770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalButtonSubmit&quot;)</value>
      <webElementGuid>de0396a0-fc74-4ddc-88f3-b65f397d4db3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ModalButtonSubmit']</value>
      <webElementGuid>f023a031-2631-4fab-beef-2c31c828c7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div/div/div/div/div/div/div/div/div/div/div/table/tbody/tr/td[2]/button</value>
      <webElementGuid>bd18fc01-38c1-4873-b642-7da4a6a4db39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items'])[2]/following::button[1]</value>
      <webElementGuid>c2f4a6c6-6010-4345-9eb3-ec1e7f40edd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sisi Panel'])[2]/following::button[1]</value>
      <webElementGuid>a5b14b1b-e14e-44c8-91fe-8c9e88c9b455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>bb1e3980-c609-4f94-910d-33dd0462735b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unsaved changes'])[1]/preceding::button[2]</value>
      <webElementGuid>02db19c4-add2-4a4d-814a-179899aa75bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>337324d4-1fca-4c90-b1a5-c1ae589acff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/table/tbody/tr/td[2]/button</value>
      <webElementGuid>312d91a9-985a-4ec6-b136-ae283d1a9947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ModalButtonSubmit' and @type = 'button' and @title = 'Click here to submit work' and @alt = 'Click here to submit work' and (text() = '  Submit ' or . = '  Submit ')]</value>
      <webElementGuid>e9aeba7f-25b9-4954-a641-d9e15592af54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
