<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Upload Foto Kerusakan_pega_ui_mask</name>
   <tag></tag>
   <elementGuidId>3a317c10-94e6-489b-8643-8526e53dde1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pega_ui_mask</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pega_ui_mask']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94eeeeea-6c0e-4a9d-92e9-6146e3d505bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pega_ui_mask</value>
      <webElementGuid>46b43f7c-bcde-4834-b00e-26fcb033f308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pega_ui_masking</value>
      <webElementGuid>b647fce5-798d-4d3f-bbfb-75a6b72bf8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pega_ui_mask&quot;)</value>
      <webElementGuid>eaf98746-3a69-449b-87a6-d8f31988f54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pega_ui_mask']</value>
      <webElementGuid>3cff39c7-0f91-4ad0-8af2-9f851ad9602e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Foto Kerusakan'])[1]/preceding::div[11]</value>
      <webElementGuid>22107119-3a7a-4987-82a0-1e31e0544036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Foto Kerusakan'])[2]/preceding::div[12]</value>
      <webElementGuid>58c8fcae-2ee9-45fb-bd48-8d700b221d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>a1f40c01-7f88-4f30-8f12-484a14457a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pega_ui_mask']</value>
      <webElementGuid>62f4e20c-166c-4504-aad1-e111924f3c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
