<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Pilih Sisi Foto ---Tampak DepanT_1a682b_1</name>
   <tag></tag>
   <elementGuidId>7b6e86f1-9c70-44a4-9694-943d5812f982</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#80f7db7d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='80f7db7d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>387b3ff9-2ed3-4de9-833a-13c702df2c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>8262c246-6bec-468b-b7f1-78a8e6c4fc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20220519152237055633251</value>
      <webElementGuid>aaaeaa50-c9c3-4384-98af-42b76b7f2ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>80f7db7d</value>
      <webElementGuid>6eb0192b-9807-4394-a4cf-038d91d76ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PdragDropFileUpload$ppxResults$l2$pSisiFoto</value>
      <webElementGuid>57154da5-7a63-4593-a88c-9e33341f9152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;PanelSide=#~dragDropFileUpload.pxResults(2).SisiFoto~#&amp;NoPolisi=#~TempNoPolisiFromList.IDPEGA~#&quot;, &quot;&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ZmZiNWYzN2RmYzQwNTVhNjhjN2VmNGQ3OGI1OWVjZTRhZGFiN2Y3MmQ4MTkzMWI0Mzk5MGYzZmZjMWEyOTRlNmE1YzhlM2QwNGQwYjA0NmIzYzlmZmJhNzNiYTY5OTQ3ZmU5YzAxMmNiOTEzNDRjNzk2MjQxY2ZjYjc1NDc1MDViYTQzNzA3YWY4ZWRmOWMyYjg4YmYwNjljYzM5NTExMg%3D%3D*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;ShowListPanelKerusakanUpload_Sec&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ODdmOTI4ZjI5YzgwZTQ3MjZlMjYwNGYxY2ZlYWVlNzc5N2Q0YjZkY2NjNDA3ZTQxYzVkN2VhYTI2OGMwNDBmOGJkNTZlOTQwYmQ0OTk1NGZmMjRhMTFhNmZlNGVmYzdkYzI0YmM0ODg5MWY4N2RhZTMxZGE1OTZhMjE0YTFjZGM4ZmIzMjNlODY3YThjZjMzNDNiZjc0MTY1NmUwY2NlM2Q2MTgzNzYyZmFiYTMxODcwNmY1M2E1ZDMxYzg1NTkxYWM0ZWNhOTUzNmVkZjFmNDc3NzYxNmZmM2NhY2ZkMTI%3D*&quot;,{},{}],&quot;&quot;]]]</value>
      <webElementGuid>613754ae-7cfa-44fc-8678-9da6e1c09c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--- Pilih Sisi Foto ---Tampak DepanTampak BelakangTampak KiriTampak KananTampak AtasTampak Bawah</value>
      <webElementGuid>604e9be2-a335-4c7e-86a1-bbc5521d7f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;80f7db7d&quot;)</value>
      <webElementGuid>83e42e71-5a17-4b3e-a90c-58fce6671b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='80f7db7d']</value>
      <webElementGuid>ad61acd9-561b-44ae-8e3f-992ba8a91efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PdragDropFileUpload$ppxResults$l2']/td[3]/div/select</value>
      <webElementGuid>aaf0acbc-4a8a-4fcf-851f-7de0b3b45c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depan'])[1]/following::select[1]</value>
      <webElementGuid>1b7889f6-96c2-4bf1-95c0-b9d517a93b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items'])[1]/following::select[1]</value>
      <webElementGuid>185823b8-b99b-4bd1-9dc4-ea9dc0960f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[3]/preceding::select[1]</value>
      <webElementGuid>3cdcad2a-c0e3-4b67-94c4-5326a4ae6d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panel'])[2]/preceding::select[1]</value>
      <webElementGuid>e1a87274-e339-4e29-b0b7-de0cb6bb6762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/select</value>
      <webElementGuid>daceff1e-d469-4d94-93c8-52bf23d04747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '80f7db7d' and @name = '$PdragDropFileUpload$ppxResults$l2$pSisiFoto' and (text() = '--- Pilih Sisi Foto ---Tampak DepanTampak BelakangTampak KiriTampak KananTampak AtasTampak Bawah' or . = '--- Pilih Sisi Foto ---Tampak DepanTampak BelakangTampak KiriTampak KananTampak AtasTampak Bawah')]</value>
      <webElementGuid>b26c8e83-391b-455d-83c3-01c50eab7720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
