<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Pilih Sisi Foto ---Tampak DepanT_1a682b</name>
   <tag></tag>
   <elementGuidId>4244f38d-83d4-4f30-a496-0d170abfdcf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1915bd7c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='1915bd7c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>09bd7445-390c-4fb1-94e8-4007515891fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>df2cbef8-2e4f-412a-94ef-51840abc8ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20220519152237055633251</value>
      <webElementGuid>0229e17c-268e-4f6e-900c-a20b270ed829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1915bd7c</value>
      <webElementGuid>66d6821d-9cd4-41a4-91c9-c4a65812148d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PdragDropFileUpload$ppxResults$l1$pSisiFoto</value>
      <webElementGuid>a5c97704-0a62-455e-acfa-6fa9a7a62231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]],[&quot;runActivity&quot;, [&quot;&quot;, &quot;PanelSide=#~dragDropFileUpload.pxResults(1).SisiFoto~#&amp;NoPolisi=#~TempNoPolisiFromList.IDPEGA~#&quot;, &quot;&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ZmZiNWYzN2RmYzQwNTVhNjhjN2VmNGQ3OGI1OWVjZTRhZGFiN2Y3MmQ4MTkzMWI0Mzk5MGYzZmZjMWEyOTRlNmE1YzhlM2QwNGQwYjA0NmIzYzlmZmJhNzNiYTY5OTQ3ZmU5YzAxMmNiOTEzNDRjNzk2MjQxY2ZjYjc1NDc1MDViYTQzNzA3YWY4ZWRmOWMyYjg4YmYwNjljYzM5NTExMg%3D%3D*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;ShowListPanelKerusakanUpload_Sec&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ODdmOTI4ZjI5YzgwZTQ3MjZlMjYwNGYxY2ZlYWVlNzc5N2Q0YjZkY2NjNDA3ZTQxYzVkN2VhYTI2OGMwNDBmOGJkNTZlOTQwYmQ0OTk1NGZmMjRhMTFhNmZlNGVmYzdkYzI0YmM0ODg5MWY4N2RhZTMxZGE1OTZhMjE0YTFjZGM4ZmIzMjNlODY3YThjZjMzNDNiZjc0MTY1NmUwY2NlM2Q2MTgzNzYyZmFiYTMxODcwNmY1M2E1ZDMxYzg1NTkxYWM0ZWNhOTUzNmVkZjFmNDc3NzYxNmZmM2NhY2ZkMTI%3D*&quot;,{},{}],&quot;&quot;]]]</value>
      <webElementGuid>21dda80b-c0c5-4ef2-b112-1635f09fb867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--- Pilih Sisi Foto ---Tampak DepanTampak BelakangTampak KiriTampak KananTampak AtasTampak Bawah</value>
      <webElementGuid>f5188d15-0624-443d-b751-19e216f86498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1915bd7c&quot;)</value>
      <webElementGuid>78c242d3-1511-43dd-95a9-c6223e286cf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='1915bd7c']</value>
      <webElementGuid>1b332490-500a-4dde-a739-f116559ef35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PdragDropFileUpload$ppxResults$l1']/td[3]/div/select</value>
      <webElementGuid>29ff5adb-ccd2-489a-8958-0d6e43f6a0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belakang'])[1]/following::select[1]</value>
      <webElementGuid>31a7e289-21e5-4c0f-aff8-cb195205683a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sisi Foto'])[1]/following::select[1]</value>
      <webElementGuid>0d06b18c-60aa-4078-8968-23d9ad0460d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[1]/preceding::select[1]</value>
      <webElementGuid>ec3207bf-4bd1-4f00-b033-679a914392e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panel'])[1]/preceding::select[1]</value>
      <webElementGuid>5b007891-13c6-45c3-a4cb-455f6e192d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c2c671ae-de22-4e21-8bc3-0998702cee4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '1915bd7c' and @name = '$PdragDropFileUpload$ppxResults$l1$pSisiFoto' and (text() = '--- Pilih Sisi Foto ---Tampak DepanTampak BelakangTampak KiriTampak KananTampak AtasTampak Bawah' or . = '--- Pilih Sisi Foto ---Tampak DepanTampak BelakangTampak KiriTampak KananTampak AtasTampak Bawah')]</value>
      <webElementGuid>ed36fd85-3af6-4311-8063-22feca8afb59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
