<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tanggal Kejadian_CalendarImg-0509d02b</name>
   <tag></tag>
   <elementGuidId>ed50c521-716e-4d3a-ad1c-fae30cae6bb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;CalendarImg-0509d02b&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='CalendarImg-0509d02b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a61be66c-c463-4365-8122-63e55a05e286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>webwb/pzspacer_11792674401.gif!!.gif</value>
      <webElementGuid>a11daeed-d6ca-47c3-aae5-1d97f54338ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CalendarImg-0509d02b</value>
      <webElementGuid>c5e73d83-adcc-4452-9414-759a2746d2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactvIcon icnHvr</value>
      <webElementGuid>d679130d-7b21-42c7-b990-9b36272bd40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20201216133602055043852-DatePicker</value>
      <webElementGuid>523e5aa8-178d-488c-b746-12a12f5f34f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;DatePicker&quot;]</value>
      <webElementGuid>18afa77d-a382-4f8f-9ca5-bc1ed93a0d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db3676ce-640a-463f-9251-a13ebb8f6601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1699b297-9059-4f75-8f68-805e8c7dcc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Choose from calendar</value>
      <webElementGuid>fd22c472-fde3-4c2e-802f-f35141bb71fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PWorkForm$pTglKejadianSpan&quot;)/img[@class=&quot;inactvIcon icnHvr&quot;]</value>
      <webElementGuid>5f8f59c2-cb0d-4547-9d3d-ee3308156ad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='CalendarImg-0509d02b']</value>
      <webElementGuid>177be5d9-3eff-4f47-a47a-ec5bb28903f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='$PWorkForm$pTglKejadianSpan']/img</value>
      <webElementGuid>fa586799-0f9f-476c-9d31-d850b4511096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Choose from calendar'])[2]</value>
      <webElementGuid>726d48e3-608a-4671-8f91-4abeb81b52c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/img</value>
      <webElementGuid>3efec0e3-1f7f-4c01-951c-88bf22a12e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'webwb/pzspacer_11792674401.gif!!.gif' and @name = 'CalendarImg-0509d02b' and @alt = 'Choose from calendar']</value>
      <webElementGuid>5364341e-e4fb-4e2c-93d2-14dc691ab650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
