<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tanggal Lapor_CalendarImg-0079ae87</name>
   <tag></tag>
   <elementGuidId>484ef039-7539-4bf5-a73e-908dc41ff4ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;CalendarImg-0079ae87&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='CalendarImg-0079ae87']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>550897bf-27c1-44e9-a190-bc3478915591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>webwb/pzspacer_11792674401.gif!!.gif</value>
      <webElementGuid>19f82825-ab60-468a-ad77-14347427c6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CalendarImg-0079ae87</value>
      <webElementGuid>71c72eab-7d74-4aae-8876-9dd43aced19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactvIcon icnHvr</value>
      <webElementGuid>dc0a3774-b5e7-4486-865a-2c6be2e61475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20201216133602054939247-DatePicker</value>
      <webElementGuid>47e403cd-f5dd-42f5-abde-565e1e5a6026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;DatePicker&quot;]</value>
      <webElementGuid>d8f95a14-7324-4f72-a8d3-bfa1a9286097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1f4fdce-51c3-4023-a3b1-6d8a33eebeb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12dc765c-950e-4283-954c-5f90ba8760f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Choose from calendar</value>
      <webElementGuid>188d57d7-99e1-4aa5-a932-483662d5d839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PWorkForm$pTglLaporSpan&quot;)/img[@class=&quot;inactvIcon icnHvr&quot;]</value>
      <webElementGuid>f0e2f97b-e0c5-430c-958b-1563c1f050b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='CalendarImg-0079ae87']</value>
      <webElementGuid>0da7309b-4fee-40c5-aa95-078bb96099c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='$PWorkForm$pTglLaporSpan']/img</value>
      <webElementGuid>a2ef7843-3983-414d-bda1-af4aeff6e15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Choose from calendar']</value>
      <webElementGuid>0f59db93-ade6-498c-9842-7bfb771fc142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9ff6b43c-500f-49ff-9a38-db3dec6a2f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'webwb/pzspacer_11792674401.gif!!.gif' and @name = 'CalendarImg-0079ae87' and @alt = 'Choose from calendar']</value>
      <webElementGuid>201a45b3-b4fe-4893-a4b3-1ad58f738737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
