<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload</name>
   <tag></tag>
   <elementGuidId>1eed3bdb-7c2d-4e52-bbb6-710d0d3c54cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;SurveyClaim_Sec_pyWorkPage_23&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='SurveyClaim_Sec_pyWorkPage_23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d94e683-1637-463a-8763-708f4e74e234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202012031420250432215549</value>
      <webElementGuid>123c2012-1d04-439d-82a6-c6ca60977741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;processAction&quot;, [&quot;UploadFormKlaim_FA&quot;,&quot;overlay&quot;,&quot;:event&quot;,&quot;&quot;,&quot;Rule-HTML-Section&quot;,&quot;pz-po-c-fixed_size&quot;,&quot;pzModalTemplate&quot;,&quot;%7B%22isCustomMobileAnim%22%3A%22true%22%2C%22desktop%22%3A%7B%22reveal%22%3A%7B%22ease%22%3A%22standard%22%2C%22effect%22%3A%22none%22%2C%22speed%22%3A%22default%22%7D%2C%22isCustomDismiss%22%3A%22false%22%7D%2C%22mobile%22%3A%7B%22reveal%22%3A%7B%22ease%22%3A%22standard%22%2C%22effect%22%3A%22anim-offbottom-open%22%2C%22speed%22%3A%22default%22%7D%2C%22isCustomDismiss%22%3A%22false%22%7D%7D&quot;,&quot;false&quot;,&quot;ASM-FW-ICMS-Work-FormulirClaim&quot;,&quot;ASM-FW-ICMS-Work-FormulirClaim&quot;,&quot;true&quot;,&quot;true&quot;,&quot;&quot;,&quot;&quot;]],[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;UploadForm_Sec&quot;, &quot;&quot;, &quot;=&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ZThkZDhjYmE2YjBlMGUxODE1NDg3ZGZhYmRiNDIzMWQ1ZDE1YWZhYjc0NjVhMDU5NjBjNDQwNGQ4ZDNlMmFkY2VjNmM3NTQwNWM4OWYxYmQ3MzJiNGQ0NTY0MjE2MWVkNDFhY2QwMzJhMTgwMjk5YjRkYTYyMjNjN2MzZTc3ZDg%3D*&quot;,{},{}],&quot;pyWorkPage&quot;],[&quot;&amp;&quot;,[&quot;OP&quot;,[&quot;$PRefreshSection$pIDPEGA&quot;,&quot;=&quot;,&quot;1&quot;,&quot;false&quot;]]]]]</value>
      <webElementGuid>2ef8d2ae-4cc3-4681-b375-4decd7d5dbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SurveyClaim_Sec_pyWorkPage_23</value>
      <webElementGuid>4619a161-b115-4de9-8875-0b037e3ec08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>5d82ceba-d7d5-4af7-9949-12cfbdefaafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcee366f-4eb6-4f0e-96be-51912e069213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>e8496d4a-b643-49a3-858b-f2c406e41b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-none&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[1]/div[@class=&quot;content layout-content-default  content-default clearfix&quot;]/div[@class=&quot;content-item content-layout item-2&quot;]/div[@class=&quot;content-inner&quot;]/div[@id=&quot;EXPAND-OUTERFRAME&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>9278cfe6-00ea-46fa-b3ed-0adc875a835a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='SurveyClaim_Sec_pyWorkPage_23']</value>
      <webElementGuid>78486172-25a6-4829-a938-ea069e863db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/span/button</value>
      <webElementGuid>26839833-bb55-4815-ac52-c3f8992736a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File Form Klaim'])[1]/following::button[1]</value>
      <webElementGuid>2110f68e-ace3-4ae0-bafa-e974534b8763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit &amp; Cetak Formulir Klaim'])[2]/following::button[1]</value>
      <webElementGuid>b1a84129-4955-4f55-aa85-d824d0cb41d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak Formulir Klaim'])[1]/preceding::button[1]</value>
      <webElementGuid>f2454664-9c7d-4d0e-a741-62f364cd6f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambar'])[1]/preceding::button[2]</value>
      <webElementGuid>d275e050-19f1-4900-8781-772785b25f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload']/parent::*</value>
      <webElementGuid>0b71a478-8614-4106-939a-92ccf8044647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/button</value>
      <webElementGuid>fda37bf2-afa7-4ac3-ba38-5b3240b27890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'SurveyClaim_Sec_pyWorkPage_23' and @type = 'button' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>df30df77-dc74-4a54-93bf-c21efc4d7626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
