<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tanggal Kejadian_CalendarImg-0509d02b</name>
   <tag></tag>
   <elementGuidId>f6230fbb-a0f6-45a0-af10-6e21babd7dc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;CalendarImg-0509d02b&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='CalendarImg-0509d02b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f2942d49-2bcf-43ad-9c80-68533bb4ad21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>webwb/pzspacer_11792674401.gif!!.gif</value>
      <webElementGuid>25e6e3a7-2e30-4ae9-af85-5620e90eea19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CalendarImg-0509d02b</value>
      <webElementGuid>3ecd9b52-b2e6-46dd-b648-30fea4036687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactvIcon icnHvr</value>
      <webElementGuid>33ad48e3-7cd5-4352-87e6-254ea5cea66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20201216133602055043852-DatePicker</value>
      <webElementGuid>9b5d575e-d01e-4bd9-b034-44e76bdf8d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;DatePicker&quot;]</value>
      <webElementGuid>b1c5b6b2-96d0-4c51-8d75-38d109853c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec9276ed-2ab9-48b4-97f6-758c2c809056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8eba9dd7-ca7f-4e8f-809a-bcc06a5ee789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Choose from calendar</value>
      <webElementGuid>577d8136-615d-439b-92c0-c1419bf9fa61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PWorkForm$pTglKejadianSpan&quot;)/img[@class=&quot;inactvIcon icnHvr&quot;]</value>
      <webElementGuid>86dfd6c7-ed35-4c6f-b812-67b386b0d78f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='CalendarImg-0509d02b']</value>
      <webElementGuid>3275b339-2302-457f-ac43-b70dbda11fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='$PWorkForm$pTglKejadianSpan']/img</value>
      <webElementGuid>c6ab7d8c-284d-4a23-b9a2-4010aa22350f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Choose from calendar'])[2]</value>
      <webElementGuid>3a14f465-d366-4d3a-a27d-10ee88baa2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/img</value>
      <webElementGuid>18fa864e-6ad2-4f02-9f35-c525f36d8db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'webwb/pzspacer_11792674401.gif!!.gif' and @name = 'CalendarImg-0509d02b' and @alt = 'Choose from calendar']</value>
      <webElementGuid>ac84df9f-4235-4d2f-b7bc-311edceef25c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
