<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tanggal Lapor_CalendarImg-0079ae87</name>
   <tag></tag>
   <elementGuidId>bf2ac616-6a71-466f-a7e2-5d07502f8c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;CalendarImg-0079ae87&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='CalendarImg-0079ae87']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3f70d46b-7571-475c-88de-cf0667e14f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>webwb/pzspacer_11792674401.gif!!.gif</value>
      <webElementGuid>23c64beb-0fe0-47d5-98d1-de22844e770a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CalendarImg-0079ae87</value>
      <webElementGuid>5e72a188-3d96-4abf-ae10-4f7d8bf2a0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inactvIcon icnHvr</value>
      <webElementGuid>a9c6c89a-ea66-4c90-8473-d7a803d86f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>20201216133602054939247-DatePicker</value>
      <webElementGuid>9dc761ac-81ac-42a1-b5ed-ed8f581ee4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;DatePicker&quot;]</value>
      <webElementGuid>0a16bc35-08ab-49f2-8e0f-65a4038aac3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>89226b56-d048-4fcf-ac76-9161d1f3db7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b9468a3-53c1-4559-a71d-acd2d6e0376a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Choose from calendar</value>
      <webElementGuid>8b182f8a-4952-4627-ae2a-d06a3b63c42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PWorkForm$pTglLaporSpan&quot;)/img[@class=&quot;inactvIcon icnHvr&quot;]</value>
      <webElementGuid>c64c6144-cc23-43fa-9ca6-d12ca736a533</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='CalendarImg-0079ae87']</value>
      <webElementGuid>0de74c2f-46c2-4198-92ec-3bdeee226c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='$PWorkForm$pTglLaporSpan']/img</value>
      <webElementGuid>01593b8b-199b-449f-bc6c-a9656d1e26a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Choose from calendar']</value>
      <webElementGuid>87db1f56-1eae-4f02-869d-026ba877b056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b0139614-824c-43e0-bbc7-90442d6334c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'webwb/pzspacer_11792674401.gif!!.gif' and @name = 'CalendarImg-0079ae87' and @alt = 'Choose from calendar']</value>
      <webElementGuid>0a757892-2fce-42b7-addc-d5a9a2b91696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
