<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Mesin_PWorkFormpPolisNoMesin</name>
   <tag></tag>
   <elementGuidId>106c767b-43f6-44da-8162-019518d3e857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acbb741a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acbb741a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c539791b-bfc1-459c-97db-0e0c111f1007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>80fa03dd-90bf-45f3-9cf1-5376853c6043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202012161343120724444680</value>
      <webElementGuid>8eeac6d3-c7fe-4754-a6de-d73e8886f1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>168ed3fd-afbe-4738-b7c8-863bec7d3efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ab1b785-699f-45ba-add7-0defef1cead5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acbb741a</value>
      <webElementGuid>20d336e4-6f91-4286-9094-304d3d7c9737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>K148T1088075</value>
      <webElementGuid>e416c918-5a1f-429d-9783-5ce06ca17298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>0c6f5885-645f-4086-abd4-0b8f046786b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PWorkForm$pPolisNoMesin</value>
      <webElementGuid>41b7c348-a122-4f7d-b829-fd58b9a78012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PWorkForm$pPolisNoMesinError</value>
      <webElementGuid>2888cf65-3ce5-48d9-94c4-5323600a6fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b25fffd0-ae89-4cf8-9d85-02ed3912702a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acbb741a&quot;)</value>
      <webElementGuid>ee032f27-48cf-4b5f-8da6-4519a6103e1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acbb741a']</value>
      <webElementGuid>7104f709-0d4e-4b0a-ae2c-94717ae1128a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/div/div[2]/div/div/div/span/input</value>
      <webElementGuid>d238c092-7742-40bb-8fbf-e63eb856eb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div[2]/div/div/div/span/input</value>
      <webElementGuid>48e57ad5-d1cf-40af-a9a6-4ace1062d5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'acbb741a' and @name = '$PWorkForm$pPolisNoMesin']</value>
      <webElementGuid>c55e227b-c13e-4248-9763-fb6fd509682f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
