<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Required_PWorkFormpPolisNo</name>
   <tag></tag>
   <elementGuidId>8760efad-6a43-4289-897e-2640ddc50c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PolisNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PolisNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6d4d85a-ae24-42c8-9fbd-036fee44d110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8b500754-e235-4851-9d9d-543e6d5a04ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>non-auto</value>
      <webElementGuid>b3a71bac-e58a-4e34-9f26-964acf23170e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>9c12ae1b-5754-416b-856d-4d42bce05f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationtype</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a90bd561-a470-4566-85f4-422f4a34f584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PolisNo</value>
      <webElementGuid>cd80d94b-914e-4c8d-91c9-8ad86b7a4a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>1dfd781c-862f-427d-b6c1-756c452c9019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a26e30a-0458-42c0-bf88-da65089d0c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PWorkForm$pPolisNo</value>
      <webElementGuid>1df06178-2392-4ce3-a45d-10ba1e6fded8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57d163b3-beb8-4882-a6f8-bd1b66cee2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolisNo&quot;)</value>
      <webElementGuid>3d269a40-f31f-4a9f-a6e4-e54c78db351f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PolisNo']</value>
      <webElementGuid>918e2614-b377-4908-87a3-585e3905c059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>8fe95099-9ea4-4e7e-8f10-ded8cdcd4422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>baac92fd-734d-44e0-af21-ee64441136ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PolisNo' and @type = 'text' and @name = '$PWorkForm$pPolisNo']</value>
      <webElementGuid>189c9cc2-d755-473e-ba52-3ae6107e762f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
