<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Rangka_PWorkFormpPolisNoRangka</name>
   <tag></tag>
   <elementGuidId>9cfc72d8-77a1-45b5-87b4-efae121f56ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c7e3bcce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c7e3bcce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71e4060f-33d7-4326-bffb-942a81cd249e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>f2264968-4c12-4997-ab1d-403d4dcbb333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202012161343120724443102</value>
      <webElementGuid>4170e303-feb2-4d70-a60c-208e1cfd8fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;TextInput&quot;]</value>
      <webElementGuid>1df340c1-7638-4a73-9ccb-ed407a779107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08b32c9d-acf3-43b6-8f5a-cf140c53d46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c7e3bcce</value>
      <webElementGuid>1a238e98-5b1b-4a7b-8933-478bd38987d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>MHYKZE81SDJ228149</value>
      <webElementGuid>954e4c0b-9673-4cbc-b653-f624f44e1d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leftJustifyStyle</value>
      <webElementGuid>4acb01ca-ec96-461a-b38d-e60c88287409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PWorkForm$pPolisNoRangka</value>
      <webElementGuid>9c3f2304-629b-4ec5-95bb-4ff571811dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>$PWorkForm$pPolisNoRangkaError</value>
      <webElementGuid>a3d8e687-8a14-4234-a3a2-7218ee1961f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e7151b2-00e4-44a2-82d2-a7d65c85420a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c7e3bcce&quot;)</value>
      <webElementGuid>f2e64334-d2a5-4906-ad29-963bc0b85465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c7e3bcce']</value>
      <webElementGuid>a4da8707-9163-4db4-ace4-3cd8aa324d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EXPAND-OUTERFRAME']/div[2]/div/div/div/div[2]/div/div[2]/div/span/input</value>
      <webElementGuid>631449fc-ee26-4b17-bce6-5e8787143ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/span/input</value>
      <webElementGuid>0566be14-d133-4dc9-8459-8f8b424597c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'c7e3bcce' and @name = '$PWorkForm$pPolisNoRangka']</value>
      <webElementGuid>80b49f51-8043-4bf0-b695-df96dc804008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
