<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Ya</name>
   <tag></tag>
   <elementGuidId>87da3ad4-bb67-41a4-ba96-4c4691621e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.rb_.rb_standard.radioLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RULE_KEY']/div[4]/div/div/div/div/div/div/div/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>00c89139-c071-43ce-8b61-3d02a25dfb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>210b947ftrue</value>
      <webElementGuid>71c3693c-0546-4511-b01c-ba91e3ec5f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>631e9464-9d9f-4460-a3f1-1791357d6d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rb_ rb_standard radioLabel</value>
      <webElementGuid>cfd85e6c-6693-4b16-8a00-8dd22b7488bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>50d45e61-2f0a-48f1-9833-59e1e5e4b792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pyFlowActionHTML&quot;)/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-sub_section item-1 flex flex-row&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-layout item-1 flex flex-row&quot;]/div[1]/div[@class=&quot;flex content layout-content-default  content-default&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing remove-bottom-spacing remove-right-spacing flex required&quot;]/div[@class=&quot;field-item dataValueWrite&quot;]/div[@class=&quot;radioTable&quot;]/div[1]/span[@class=&quot;col-1&quot;]/label[@class=&quot;rb_ rb_standard radioLabel&quot;]</value>
      <webElementGuid>9344fed4-6dab-4eeb-8e98-684fa60b539e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[4]/div/div/div/div/div/div/div/span/label</value>
      <webElementGuid>980d3eb7-f49f-4a4a-9251-efe27f80a258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Data Polis Sama Dengan Data Pelapor?'])[1]/following::label[1]</value>
      <webElementGuid>230323f4-2dd3-43be-b4af-dfe537d6ab03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/following::label[2]</value>
      <webElementGuid>1bc51eab-92ee-45c1-ba6f-da973614ccb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/preceding::label[1]</value>
      <webElementGuid>9b03de77-ad87-4bc5-93a1-cf2c3721d5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pelapor'])[1]/preceding::label[2]</value>
      <webElementGuid>ef7e1cae-7d1c-4194-a302-94bb4058b9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ya']/parent::*</value>
      <webElementGuid>1632a33e-55e9-4706-b866-8123000f2d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>4606c1e7-25fd-4190-b1ad-d6d58dff114f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Ya' or . = 'Ya')]</value>
      <webElementGuid>aed5c315-7d1b-4cbb-83c1-df066b7f8db6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
