<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TESTING ASM</name>
   <tag></tag>
   <elementGuidId>1773d44b-f550-4edb-8b66-1331083dd4fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.match-highlight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='$PGetWilayahKlaim$ppxResults$l1']/td/div/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38588e0d-dfbd-4bc8-b20a-b8a59e7bf6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>match-highlight</value>
      <webElementGuid>40970ced-8f8e-4e31-b170-b3f8423b3f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TESTING ASM</value>
      <webElementGuid>1f28223a-3d49-492e-843a-df5913a2b4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PGetWilayahKlaim$ppxResults$l1&quot;)/td[@class=&quot;autocompleteAGleft gridCell gridCellSelected&quot;]/div[@class=&quot;oflowDiv&quot;]/div[@class=&quot;divCont&quot;]/div[@class=&quot;cellIn&quot;]/span[1]/span[@class=&quot;match-highlight&quot;]</value>
      <webElementGuid>b87855df-1167-4b36-9a5b-525c47e5d1b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='$PGetWilayahKlaim$ppxResults$l1']/td/div/div/div/span/span</value>
      <webElementGuid>f73f7985-0952-4e0c-83a3-d19aefaa9f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IdWilayahKlaim'])[1]/following::span[3]</value>
      <webElementGuid>772b2d5a-77bd-48b6-8e28-968461de5952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit &amp; Cetak Formulir Klaim'])[2]/following::span[5]</value>
      <webElementGuid>9b82cf2c-9d58-42e2-a867-e4b4023ee321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESTING ASM'])[2]/preceding::span[2]</value>
      <webElementGuid>4fe9793f-8e54-4e43-9894-a0cf2fa36d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live UI'])[1]/preceding::span[4]</value>
      <webElementGuid>27f72b4c-c999-4950-9542-d9613d9975c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TESTING ASM']/parent::*</value>
      <webElementGuid>f19158cb-5437-417f-9f9f-31400df95ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/span/span</value>
      <webElementGuid>bfbba589-515e-484f-a1ff-d5b4332c49d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TESTING ASM' or . = 'TESTING ASM')]</value>
      <webElementGuid>417bdac8-6161-4f24-8243-08671d180678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
