<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UploadForm</name>
   <tag></tag>
   <elementGuidId>1b4df416-c5b6-48f1-945d-3b95d2981abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='$PpyAttachmentPage$ppxAttachName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c222eda-a30c-4ed7-a4f6-783463166070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>4dc510b6-5c82-499b-b1e5-d0a65b1608a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>929653bd-ff92-4b64-a7e9-0435d41cfdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PpyAttachmentPage$ppxAttachName</value>
      <webElementGuid>b0ae7c5c-40af-4441-adc0-a83606c84e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select files</value>
      <webElementGuid>fb385639-561c-48df-ac0d-7fecc37ca414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>$PpyAttachmentPage$ppxAttachName</value>
      <webElementGuid>b8f56012-b5e1-4c8e-b23b-73b71b66e264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>be678098-dacb-46c4-bd40-32c76a502478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>516c62e0-eb2d-4cf1-8e4f-1363f7069063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>pzMultiFile_fileSelected(this, event);</value>
      <webElementGuid>7c2c3341-43b6-40c2-a329-b3935c0c046b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$PpyAttachmentPage$ppxAttachName&quot;)</value>
      <webElementGuid>391b3e52-8169-4e8f-b7a3-d96dc1559127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='$PpyAttachmentPage$ppxAttachName']</value>
      <webElementGuid>ae8e8158-d295-4d4e-a8a3-cc4243538142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div/div/input</value>
      <webElementGuid>bde29b60-2398-4707-8078-ae0797115107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>4d550fae-a80b-4d12-b075-7829515d30c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = '$PpyAttachmentPage$ppxAttachName' and @title = 'Select files' and @id = '$PpyAttachmentPage$ppxAttachName']</value>
      <webElementGuid>a43a9ad9-8fc7-4244-83e7-5650b46ecbdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
