<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>80918de9-bfac-407a-83e1-3fa62aa58812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;UploadFotoPanel_pyWorkPage_98&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='UploadFotoPanel_pyWorkPage_98']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a80c716a-4af1-4cc3-b3ec-badbe4f03785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202101061013140464130577</value>
      <webElementGuid>d7cb8bb0-d2d7-470b-9b9c-87b15a99ab81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;pyWorkPage&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ZGIyNGI1NWQzZDkzZWQ5YWY5ZWFlNmY3YzNkMmZiZDFlOTlkNDBhMWE0NzhiOTFkMzI5MGM4NjkzYzUyODBiMTAwYjEzYTM4NmJkY2MwM2U0ZTE2ZGMzOGEyYTNhOWYzZTEzZTAwZjg5MTBiMjhjZjE5Zjg2NmFiZmNjZWE4NjE%3D*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;ViewUploadFileForm&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9M2Q0MjM2N2MwYjQ1ZmRkMGRjZTE0ZThiNDc0NjY0NjUwY2JmOWRkMjU1OTRiZGI0ZjUzOGY1YjJkMjNmY2U0NzI0YmY1ODI1M2Q5MGQ0ZDU1MjhlZWJiNzI2ZmVjNjhhMzY3NTgxYjQ1NDY4MTJjYjViZDhiNjY5NDJlOWY5MDIxZmM2OWQ4ZGU5YjkwMmUyOTVkZDA3YTI3ZDY0ZmNmMzliODViZDMyMGUxZGFkYzM0NTBjMGNiMmE3MzZmMDNhMmI2MGU0NjFmMTMwYjM2YTgxOGZlYmYzYmM2Zjg4NTU4YzE4MTE0OGQ5MWJjMmE4MTg1YWVkMTUxYTYwY2ZhMmU3YmMxNjU4N2E3YTFiOWI1NzJmZTQzYTAwNGRlNTM5YjczNzk4NzQwMGYwMTE2M2EzYzUyY2ExMzM0MTg5YzE5Y2I1MWQ2NDMwNjhhNGQ5MDUzN2UwNzBhZmZiODNjOThiYWRiZDcwMjQxYTU1MzZjNWM1MGMxM2I4OTU1ZWUxZTczNjVkNTlhM2M3YmU4MWU1MDY5NTZlODRlZWZhZWE%3D*&quot;,{&quot;idForm&quot;:&quot;&quot;,&quot;Jenisform&quot;:&quot;&quot;},{}],&quot;pyWorkPage&quot;]]]</value>
      <webElementGuid>3eeaa141-454e-4f01-a49a-f3ff66f2950f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadFotoPanel_pyWorkPage_98</value>
      <webElementGuid>fa6056ad-69f0-4a6c-9486-d0335577322b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pzhc pzbutton</value>
      <webElementGuid>c0ecc1f7-8bc5-4995-bf38-54eb195de868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0f21385-0dba-49bf-9401-387c0895db05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>0674aedb-32c8-40f1-b259-932c9f2a7940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HARNESS_CONTENT&quot;)/div[@class=&quot;workarea-view-scroll-wrapper&quot;]/section[@class=&quot;workarea-view-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked  content-items-maxwidth&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-left-spacing remove-right-spacing flex flex-row no-margin-bottom&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-action_area  clear-floated-layouts&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-top-spacing remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@id=&quot;pyFlowActionHTML&quot;]/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default  float-right set-width-auto&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-default  content-default set-width-auto&quot;]/div[@class=&quot;content-item content-layout item-1 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;pzhc pzbutton&quot;]</value>
      <webElementGuid>e45b1635-33e3-4b0f-9092-3d68acdeb9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0bba0beb-8b5e-417a-b368-fb8470b4bab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202101061013140464130577</value>
      <webElementGuid>58b3e6a2-027b-40dc-bddf-11367f6f3f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;runActivity&quot;, [&quot;&quot;, &quot;&quot;, &quot;pyWorkPage&quot;, &quot;:event&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9ZGIyNGI1NWQzZDkzZWQ5YWY5ZWFlNmY3YzNkMmZiZDFlOTlkNDBhMWE0NzhiOTFkMzI5MGM4NjkzYzUyODBiMTAwYjEzYTM4NmJkY2MwM2U0ZTE2ZGMzOGEyYTNhOWYzZTEzZTAwZjg5MTBiMjhjZjE5Zjg2NmFiZmNjZWE4NjE%3D*&quot;]],[&quot;refresh&quot;, [&quot;thisSection&quot;,&quot;&quot;, &quot;ViewUploadFileForm&quot;, &quot;&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9M2Q0MjM2N2MwYjQ1ZmRkMGRjZTE0ZThiNDc0NjY0NjUwY2JmOWRkMjU1OTRiZGI0ZjUzOGY1YjJkMjNmY2U0NzI0YmY1ODI1M2Q5MGQ0ZDU1MjhlZWJiNzI2ZmVjNjhhMzY3NTgxYjQ1NDY4MTJjYjViZDhiNjY5NDJlOWY5MDIxZmM2OWQ4ZGU5YjkwMmUyOTVkZDA3YTI3ZDY0ZmNmMzliODViZDMyMGUxZGFkYzM0NTBjMGNiMmE3MzZmMDNhMmI2MGU0NjFmMTMwYjM2YTgxOGZlYmYzYmM2Zjg4NTU4YzE4MTE0OGQ5MWJjMmE4MTg1YWVkMTUxYTYwY2ZhMmU3YmMxNjU4N2E3YTFiOWI1NzJmZTQzYTAwNGRlNTM5YjczNzk4NzQwMGYwMTE2M2EzYzUyY2ExMzM0MTg5YzE5Y2I1MWQ2NDMwNjhhNGQ5MDUzN2UwNzBhZmZiODNjOThiYWRiZDcwMjQxYTU1MzZjNWM1MGMxM2I4OTU1ZWUxZTczNjVkNTlhM2M3YmU4MWU1MDY5NTZlODRlZWZhZWE%3D*&quot;,{&quot;idForm&quot;:&quot;&quot;,&quot;Jenisform&quot;:&quot;&quot;},{}],&quot;pyWorkPage&quot;]]]</value>
      <webElementGuid>a5350fe4-eb3c-47d0-b714-f85be68314d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadFotoPanel_pyWorkPage_98</value>
      <webElementGuid>0a44969a-54e9-4303-a3b1-3a68ce6c4ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pzhc pzbutton</value>
      <webElementGuid>75cf2e26-1fa0-49e8-9db5-becdb4a90956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>324508e4-0029-45a2-857f-aeb6079dd37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>338b5738-183c-461a-9270-db21f4c2617a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HARNESS_CONTENT&quot;)/div[@class=&quot;workarea-view-scroll-wrapper&quot;]/section[@class=&quot;workarea-view-content&quot;]/div[@id=&quot;RULE_KEY&quot;]/span[@class=&quot;inspector-span&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked  content-items-maxwidth&quot;]/div[@class=&quot;content-item content-sub_section item-1 remove-left-spacing remove-right-spacing flex flex-row no-margin-bottom&quot;]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-action_area  clear-floated-layouts&quot;]/div[@class=&quot;layout-body clearfix&quot;]/div[@class=&quot;flex content layout-content-stacked  content-stacked&quot;]/div[@class=&quot;content-item content-sub_section item-2 remove-top-spacing remove-left-spacing remove-right-spacing flex flex-row&quot;]/div[@id=&quot;pyFlowActionHTML&quot;]/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;layout layout-noheader layout-noheader-default  float-right set-width-auto&quot;]/div[@class=&quot;layout-body&quot;]/div[@class=&quot;flex content layout-content-default  content-default set-width-auto&quot;]/div[@class=&quot;content-item content-layout item-1 flex flex-row&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;pzhc pzbutton&quot;]</value>
      <webElementGuid>8827a24c-bdc0-4034-9662-1797911a368f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='UploadFotoPanel_pyWorkPage_98']</value>
      <webElementGuid>42643581-dfc0-4b31-8c89-04e03c8e26a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[6]/div/div/div/div/div/span/button</value>
      <webElementGuid>82722b01-ab0b-44c3-bd65-46528b82bfad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No items'])[1]/following::button[1]</value>
      <webElementGuid>f0808642-93f0-420d-b4d0-34cc9792fe9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter to sort'])[5]/following::button[1]</value>
      <webElementGuid>9eac3b98-cbcd-4de4-ab05-482cfb4c5b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::button[1]</value>
      <webElementGuid>3a627605-ff9f-4ff5-b50f-f41d57fecb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UploadDokumenFormClaimAllDocument_FA'])[1]/preceding::button[2]</value>
      <webElementGuid>f87bd6be-0efa-47d8-864d-1abfecaec9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>110a414f-0616-47c2-a4be-5b5ec34d61e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/span/button</value>
      <webElementGuid>42f109d0-1dc9-4f84-82d9-bfbe4b6d94a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'UploadFotoPanel_pyWorkPage_98' and @type = 'button' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>06c77534-95c2-48d5-9f40-9b9fc48534e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
