<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>bfc8dd13-292c-4cc7-921f-1ae3879a5766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;UploadDokumenFormKlaimAllDocument_Sec_pyWorkPage_6&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='UploadDokumenFormKlaimAllDocument_Sec_pyWorkPage_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b667c4f5-746c-4cd7-a241-46c58264113b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2021111617024006491653</value>
      <webElementGuid>88d4db90-ae19-4a32-829e-6232e3773729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;UploadFotoPanel&quot;, &quot;UploadDokumenFormClaimAllDocument_Act&quot;, &quot;jenisdokumen=#~pyWorkPage.pyLabel~#&amp;Category=#~TempJnsDokumenForm.IDPEGA2~#&amp;idForm=#~WorkForm.ID_Form~#&amp;inskey=#~pyWorkPage.pzInsKey~#&amp;nopolisi=#~WorkForm.PolisNoPlat~#&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9M2Q0MjM2N2MwYjQ1ZmRkMGRjZTE0ZThiNDc0NjY0NjUwY2JmOWRkMjU1OTRiZGI0ZjUzOGY1YjJkMjNmY2U0NzI0YmY1ODI1M2Q5MGQ0ZDU1MjhlZWJiNzI2ZmVjNjhhMmU2NDJjYTA5ZWE4ZDFkMjY5ZDZkMDNmNjY5Y2MzMjdiNGY0YWE3OGM5MTIxODUxN2NiMzViOTQzMjgwNmZjZGQzMzRlNjc5MWU1YjgzNWVhMjQ0YTk3ZTg5ZTlkOTE4MTc4MDI5MzUyNThmMWZjYmViZDVhNWMzMTU1NmM5ODY%3D*&quot;,{},{}],&quot;pyWorkPage&quot;]],[&quot;closeContainer&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>19396a47-3ce1-4583-b3b2-78e466e1ffb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadDokumenFormKlaimAllDocument_Sec_pyWorkPage_6</value>
      <webElementGuid>7400cfb1-acba-4a9b-bf24-b74e5df595ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>69571973-a738-4faa-a75f-68ae34a5f782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6877f5ed-1cc4-45d8-8aca-962a7362ad73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>f8434774-4ad9-401b-95a5-827e6a635dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modaldialog_con&quot;)/div[@id=&quot;pyFlowActionHTML&quot;]/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline&quot;]/div[@class=&quot;content-item content-layout item-2 align-end set-width-auto flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default set-width-auto&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing remove-bottom-spacing remove-right-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>8936788a-a2d9-4828-9596-ce8b1bbe50eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>900b44d4-eb64-4227-bcd7-e39f0e89b217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2021111617024006491653</value>
      <webElementGuid>78314ca6-1de3-4df6-84ea-2bc6ccf6f014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;UploadFotoPanel&quot;, &quot;UploadDokumenFormClaimAllDocument_Act&quot;, &quot;jenisdokumen=#~pyWorkPage.pyLabel~#&amp;Category=#~TempJnsDokumenForm.IDPEGA2~#&amp;idForm=#~WorkForm.ID_Form~#&amp;inskey=#~pyWorkPage.pzInsKey~#&amp;nopolisi=#~WorkForm.PolisNoPlat~#&quot;, &quot;&quot;, &quot;,&quot;,&quot;:event&quot;,&quot;&quot;,[&quot;pzuiactionzzz=CXt0cn17U1RBTkRBUkR9M2Q0MjM2N2MwYjQ1ZmRkMGRjZTE0ZThiNDc0NjY0NjUwY2JmOWRkMjU1OTRiZGI0ZjUzOGY1YjJkMjNmY2U0NzI0YmY1ODI1M2Q5MGQ0ZDU1MjhlZWJiNzI2ZmVjNjhhMmU2NDJjYTA5ZWE4ZDFkMjY5ZDZkMDNmNjY5Y2MzMjdiNGY0YWE3OGM5MTIxODUxN2NiMzViOTQzMjgwNmZjZGQzMzRlNjc5MWU1YjgzNWVhMjQ0YTk3ZTg5ZTlkOTE4MTc4MDI5MzUyNThmMWZjYmViZDVhNWMzMTU1NmM5ODY%3D*&quot;,{},{}],&quot;pyWorkPage&quot;]],[&quot;closeContainer&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>ac3ef877-6c72-4c8b-9e05-09908d586f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadDokumenFormKlaimAllDocument_Sec_pyWorkPage_6</value>
      <webElementGuid>c48d895a-5f18-4a99-b4d2-c21904523430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>46422a1f-84d0-4bbb-84a7-114addbe2981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49ade974-c11c-4afb-9560-b78c382e8cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>0505a754-5137-4a34-a229-d4cd12722b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modaldialog_con&quot;)/div[@id=&quot;pyFlowActionHTML&quot;]/span[1]/div[@id=&quot;RULE_KEY&quot;]/div[@class=&quot;flex content layout-content-inline  content-inline&quot;]/div[@class=&quot;content-item content-layout item-2 align-end set-width-auto flex flex-row&quot;]/div[@class=&quot;flex content layout-content-default  content-default set-width-auto&quot;]/div[@class=&quot;content-item content-field item-1 remove-top-spacing remove-left-spacing remove-bottom-spacing remove-right-spacing flex flex-row dataValueWrite&quot;]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>a3884512-52ef-4376-a985-b974e52b56b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='UploadDokumenFormKlaimAllDocument_Sec_pyWorkPage_6']</value>
      <webElementGuid>b6ecdf2e-ac72-44b7-9280-484fe3fede81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/div[2]/div[2]/div/div/span/button</value>
      <webElementGuid>71b1baed-33aa-4537-9283-0eb9a122ae7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>cb619702-198a-4d9c-af34-35ad17567491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STNK'])[3]/following::button[2]</value>
      <webElementGuid>49181e63-c385-458f-b73c-696a0c55b01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::button[1]</value>
      <webElementGuid>f528befb-aeb7-46f7-a2de-bbf8964f3ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[3]/preceding::button[2]</value>
      <webElementGuid>e1040a7f-261d-4995-a358-c2d38e86b945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/button</value>
      <webElementGuid>676ea247-57e8-45f8-beec-45234960a966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'UploadDokumenFormKlaimAllDocument_Sec_pyWorkPage_6' and @type = 'button' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>e0707ecf-75a0-4d8f-9b35-f6c2ca2aae54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
