<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload All Document</name>
   <tag></tag>
   <elementGuidId>98253f9a-5aca-4a05-954c-b343fda406af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;UploadFotoPanel_pyWorkPage_28&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='UploadFotoPanel_pyWorkPage_28']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50e67dca-a81b-4455-94af-a4d75fb36a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202012031420250432215549</value>
      <webElementGuid>5ee122e8-2810-454f-8337-9da1dfd56670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>4297d2d8-9a61-4625-8ed8-38b6ecce1bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e38d2989-8aa5-45c3-b6ef-51b50b7a1ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadFotoPanel_pyWorkPage_28</value>
      <webElementGuid>553efd17-5e60-433b-99c7-d16be4a8d113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;processAction&quot;, [&quot;UploadDokumenFormClaimAllDocument_FA&quot;,&quot;overlay&quot;,&quot;:event&quot;,&quot;&quot;,&quot;Rule-HTML-Section&quot;,&quot;pz-po-c-fixed_size&quot;,&quot;pzModalTemplate&quot;,&quot;%7B%22isCustomMobileAnim%22%3A%22true%22%2C%22desktop%22%3A%7B%22reveal%22%3A%7B%22ease%22%3A%22standard%22%2C%22effect%22%3A%22none%22%2C%22speed%22%3A%22default%22%7D%2C%22isCustomDismiss%22%3A%22false%22%7D%2C%22mobile%22%3A%7B%22reveal%22%3A%7B%22ease%22%3A%22standard%22%2C%22effect%22%3A%22anim-offbottom-open%22%2C%22speed%22%3A%22default%22%7D%2C%22isCustomDismiss%22%3A%22false%22%7D%7D&quot;,&quot;false&quot;,&quot;ASM-FW-ICMS-Work-FormulirClaim&quot;,&quot;ASM-FW-ICMS-Work-FormulirClaim&quot;,&quot;true&quot;,&quot;true&quot;,&quot;&quot;,&quot;&quot;]]]</value>
      <webElementGuid>8209c1b8-2081-4b08-bdf5-03869c143493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>f4956d6f-1070-4af0-997f-2f28bc1b25ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload All Document</value>
      <webElementGuid>c9dc9827-a778-466c-85cf-921e8bc5b0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID0&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataValueWrite&quot;]/nobr[1]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>e4a7dd44-a877-4918-8474-ca7b05c14d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8db36e6-681d-4708-981d-e57b0fd92caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>202012031420250432215549</value>
      <webElementGuid>e2162cbc-6b59-4b7b-9120-29ca69268352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>75075b87-d241-41e1-ba3b-d16b145310c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5366a1cd-da57-4361-97c2-e11e04478100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UploadFotoPanel_pyWorkPage_28</value>
      <webElementGuid>c4b99e22-7e35-4558-a1f3-0185ea026ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>[[&quot;processAction&quot;, [&quot;UploadDokumenFormClaimAllDocument_FA&quot;,&quot;overlay&quot;,&quot;:event&quot;,&quot;&quot;,&quot;Rule-HTML-Section&quot;,&quot;pz-po-c-fixed_size&quot;,&quot;pzModalTemplate&quot;,&quot;%7B%22isCustomMobileAnim%22%3A%22true%22%2C%22desktop%22%3A%7B%22reveal%22%3A%7B%22ease%22%3A%22standard%22%2C%22effect%22%3A%22none%22%2C%22speed%22%3A%22default%22%7D%2C%22isCustomDismiss%22%3A%22false%22%7D%2C%22mobile%22%3A%7B%22reveal%22%3A%7B%22ease%22%3A%22standard%22%2C%22effect%22%3A%22anim-offbottom-open%22%2C%22speed%22%3A%22default%22%7D%2C%22isCustomDismiss%22%3A%22false%22%7D%7D&quot;,&quot;false&quot;,&quot;ASM-FW-ICMS-Work-FormulirClaim&quot;,&quot;ASM-FW-ICMS-Work-FormulirClaim&quot;,&quot;true&quot;,&quot;true&quot;,&quot;&quot;,&quot;&quot;]]]</value>
      <webElementGuid>04508ce0-6057-4568-9e89-0a6077a0e1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Strong pzhc pzbutton</value>
      <webElementGuid>91c1706e-9d24-4724-811e-3b46c82808e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload All Document</value>
      <webElementGuid>4c1da709-5233-400e-9e64-4ef5b594d0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PEGA_GRID0&quot;)/div[@id=&quot;PEGA_GRID_SKIN&quot;]/div[@id=&quot;RULE_KEY&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;dataValueWrite&quot;]/nobr[1]/span[1]/button[@class=&quot;Strong pzhc pzbutton&quot;]</value>
      <webElementGuid>d5957c03-5a1e-47c6-8b61-0c07ec8f8ed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='UploadFotoPanel_pyWorkPage_28']</value>
      <webElementGuid>1121eae0-81a2-4d6a-be17-bd451e7d2bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RULE_KEY']/table/tbody/tr/td[3]/nobr/span/button</value>
      <webElementGuid>0d986960-5afd-4712-a49b-4c63eb0f7106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen (Tidak Wajib Upload)'])[1]/following::button[1]</value>
      <webElementGuid>124a88fd-f02d-4971-82d1-ebcaa38e7880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto Panel'])[2]/following::button[1]</value>
      <webElementGuid>bbae7a9d-57bd-42ba-a352-b3e9e96c302a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Dokumen'])[1]/preceding::button[1]</value>
      <webElementGuid>f0ad5026-6f1d-4bdd-8bd8-449322812ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wajib Upload'])[1]/preceding::button[1]</value>
      <webElementGuid>84af09f2-6da3-4855-bee6-f7d4070e1af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload All Document']/parent::*</value>
      <webElementGuid>269d49f0-5530-4051-8ccf-c0ab69ac913d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/span/button</value>
      <webElementGuid>cc0e7b4a-7736-4ee6-b071-02605b4c9917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'UploadFotoPanel_pyWorkPage_28' and (text() = 'Upload All Document' or . = 'Upload All Document')]</value>
      <webElementGuid>a6171754-6e7a-45bd-8e0a-5001d170ed05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
