<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih DokumenKTPSTNK</name>
   <tag></tag>
   <elementGuidId>01b16afa-9354-4691-aa04-28a455ea7fe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bb60c51d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='bb60c51d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b067335-4866-4473-9682-5ceefcac3353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>4ec873df-a2db-42e1-ab1e-4ba1870b1db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2022022311162901882248</value>
      <webElementGuid>99f6412f-b77c-4e45-b23b-1954fabe2d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bb60c51d</value>
      <webElementGuid>b9aa4fd7-f90b-46cb-83ff-85c6ad2f2c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PdragDropFileUpload$ppxResults$l1$ppyLabel</value>
      <webElementGuid>05869563-5d17-4645-8e66-54394267c9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>c8c2d3b0-35a0-4b5e-befb-ba85a3fdb460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add selected</value>
      <webElementGuid>3572e3df-fd5f-48e9-89f2-988dc19f0dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih DokumenKTPSTNK</value>
      <webElementGuid>d7e9aac1-26dc-4922-b877-5efa1d0d6da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bb60c51d&quot;)</value>
      <webElementGuid>9df8dc7b-e3b0-4254-bcca-62bca1fc64e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>64490876-0e45-49fa-8786-38ad81e94f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>8262f015-e7a0-4843-a34f-7570ff5ebe90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2022022311162901882248</value>
      <webElementGuid>557e13e4-7662-41f3-ac75-a253009d1d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bb60c51d</value>
      <webElementGuid>f34653e0-4deb-4ed8-9997-2aaa85b35bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PdragDropFileUpload$ppxResults$l1$ppyLabel</value>
      <webElementGuid>88574b95-612e-4d1e-bd8e-96f292e8d150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>fc33cbc3-38a2-4b92-9905-ed9cc30e78bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add selected</value>
      <webElementGuid>80f141bb-7c69-4e10-bbb1-8712921f61f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih DokumenKTPSTNK</value>
      <webElementGuid>b0955983-41a0-4695-847b-93f5c46c5ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bb60c51d&quot;)</value>
      <webElementGuid>6d4ffd64-8680-44df-9eb3-f157ad8665b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='bb60c51d']</value>
      <webElementGuid>e472b9f8-6fc6-4b22-9954-a23f7adad418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CT']/select</value>
      <webElementGuid>989b71b1-e635-43a0-a283-99d642dd59cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTP'])[2]/following::select[1]</value>
      <webElementGuid>f7184539-0db6-44e5-888a-440fd3cf5015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[1]/following::select[1]</value>
      <webElementGuid>1b9e220e-39a4-4d15-99e6-550d50364e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::select[1]</value>
      <webElementGuid>9d44eda2-20c7-4fe9-a358-907efc196f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[2]/preceding::select[1]</value>
      <webElementGuid>e23ba6cd-fb59-41cc-b4a1-4ffbca4bff22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c4daa088-dc46-4646-8389-96e5da4f6e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'bb60c51d' and @name = '$PdragDropFileUpload$ppxResults$l1$ppyLabel' and @title = 'Add selected' and (text() = 'Pilih DokumenKTPSTNK' or . = 'Pilih DokumenKTPSTNK')]</value>
      <webElementGuid>f7a17216-1701-4167-9ac6-c8ec7637ca29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
