<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih DokumenKTPSTNK_1</name>
   <tag></tag>
   <elementGuidId>8f665ff1-4417-43fc-8758-d2683275e329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#50577e1e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='50577e1e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34054ef7-a763-4680-9a5c-90b657269f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>dee4ad5f-fcb1-4f58-b393-0ba0e5581d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2022022311162901882248</value>
      <webElementGuid>0bf26b9f-b73e-4c98-854c-c2ff29c80755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>50577e1e</value>
      <webElementGuid>9b3e1e38-b4e1-499c-80f9-2baef0fa49d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PdragDropFileUpload$ppxResults$l2$ppyLabel</value>
      <webElementGuid>f27e305a-3cf6-4f05-b2ae-f1d49be1f9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>75c547a1-e2df-40bb-9b4f-2e8135df2e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add selected</value>
      <webElementGuid>386c9e65-2323-47ac-ad93-cdfb65c6a833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih DokumenKTPSTNK</value>
      <webElementGuid>756b865c-edbb-4698-bcde-138a8ec0c06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;50577e1e&quot;)</value>
      <webElementGuid>8b619d92-5c64-490e-b318-3910fd509d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb5b123a-e0d8-4348-9aeb-142e2824a1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctl</name>
      <type>Main</type>
      <value>[&quot;Dropdown&quot;]</value>
      <webElementGuid>5065e958-a84a-469f-aa95-3fdfaf3baa22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>2022022311162901882248</value>
      <webElementGuid>f2b125c1-46d2-4b2c-a005-ec4c8e1c73b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>50577e1e</value>
      <webElementGuid>fc12e18e-9583-4ea9-b1b3-f6cb5bbc90ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>$PdragDropFileUpload$ppxResults$l2$ppyLabel</value>
      <webElementGuid>cb8e372f-3422-4821-81ca-fe3eff10132e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-change</name>
      <type>Main</type>
      <value>[[&quot;postValue&quot;,[&quot;:event&quot;]]]</value>
      <webElementGuid>8d9ae2c1-9ea2-45a2-8e99-bfdf7c4411bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add selected</value>
      <webElementGuid>e5e73dc4-1831-4e51-8e99-85bcb7b27782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih DokumenKTPSTNK</value>
      <webElementGuid>7d9ecae0-4909-4dee-a3cc-59e04030de41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;50577e1e&quot;)</value>
      <webElementGuid>83b17147-d442-4ff9-a2b9-20b766225f94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='50577e1e']</value>
      <webElementGuid>a1e6593f-88b8-46bc-878c-fa6629e92dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='CT']/select)[2]</value>
      <webElementGuid>6989f43b-1a2f-4642-9e5f-5853f1bf860f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STNK'])[3]/following::select[1]</value>
      <webElementGuid>4899169f-1fd0-41b6-ad38-a2e724a80fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTP'])[2]/following::select[2]</value>
      <webElementGuid>e6d64134-af6b-4c4e-b2b4-285d50816f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::select[1]</value>
      <webElementGuid>b7729945-a4c0-46fa-8131-e783425a8dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[2]/preceding::select[1]</value>
      <webElementGuid>18286a64-97af-434a-a1e2-f333512ae644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/select</value>
      <webElementGuid>1cc10345-f7e5-4f13-ae11-046dad5c2f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '50577e1e' and @name = '$PdragDropFileUpload$ppxResults$l2$ppyLabel' and @title = 'Add selected' and (text() = 'Pilih DokumenKTPSTNK' or . = 'Pilih DokumenKTPSTNK')]</value>
      <webElementGuid>533ab148-0fad-45f3-b563-8621bdb7902a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
